site_name: Cosomtech empty data API
repo_url: https://github.com/Cosmo-Tech/cosmotech-empty-data-api
repo_name: Cosmo-Tech/cosmotech-empty-data-api
site_description: Empty data API example for Cosmo-Tech
site_url: https://cosmo-tech.github.io/cosmotech-empty-data-api/

theme:
  name: material
  logo: assets/logo.png
  font:
    code: Fira Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.footer
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css
  - stylesheets/templates.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascript/tablesort.js

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      title: "In this page"
      permalink: true
  - def_list
  - mkdocs-click
  - pymdownx.details
  - pymdownx.snippets:
      url_download: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg



plugins:
  - search:
      lang:
        - en
  - gen-files:
      scripts:
        - docs/scripts/generate_index.py
        - docs/scripts/generate_dependencies_markdown.py
  - mike
  - social
  - table-reader
  - awesome-nav
  - literate-nav
